### ISSUE TITLE
Lines being split

### ISSUE THREAD

**Issue by lpla** [paracrawl/b64filter#5] opened 2020-05-08 12:09 UTC
Hi. I am having an issue using `b64filter` in some Catalan tests with Apertium. Looks like given some  kind of lines, `b64filter` splits them. I was able to simplify the issue without `apertium`, so this happens with a simple `cat`:

[sentences.gz](https://github.com/paracrawl/b64filter/files/4598789/sentences.gz)

```bash
zcat sentences.gz | base64 -d | wc -l
25217
zcat sentences.gz | ~/go/bin/b64filter cat - | base64 -d | wc -l
2020/05/08 13:50:34 b64filter.go:198: writeDocs: written 100 docs, 4992 lines in 23.551143ms
2020/05/08 13:50:34 b64filter.go:198: writeDocs: written 200 docs, 18275 lines in 46.941439ms
2020/05/08 13:50:35 b64filter.go:274: processed 252 documents
25469
```

See that the `wc -l` of all lines in the input base64 decoded documents is **25217** and in the output after using `cat -` with `b64filter` gets more lines (**25469**).

This generates wrong output files using translation engines, as the translations don't belong to the sentences they are attached to.

In case you can't reproduce the same output as I did in the example, here I attach it (differences start at line 137):

[sentences_output.gz](https://github.com/paracrawl/b64filter/files/4598827/sentences_output.gz)

**Comment by jelmervdl** [comment] 2020-05-08 13:36
The difference is exactly the number of documents, so I think it has to do with b64filter adding a newline at the end of the document if there isn't one:

To confirm:
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/198639/81410276-5f392c80-9138-11ea-9792-be79257d3233.png">
Left: plain file, right output of b64filter. The ^@ is the document separator to show where the first document ends and the second begins.

The 25469 lines is the correct count. 25217 is caused by base64 concatenating the last sentence of the previous document to the next.

Edit: I'm not sure how to resolve this though. If we want b64filter and any other tool that works on the base64 input to keep track of whether the document ended with a newline or not we would need to change them all from using getline() like behaviour to something else that doesn't consume the newline. Edit 2: more importantly, allowing to omit the newline at the end of the document breaks compatibility with the `zcat | base64 -d` workflow.

**Comment by jelmervdl** [comment] 2020-05-18 13:00
I'll close this issue for now. But it's something that we might want to write down: most of our tools will add a newline character to the last line even if there wasn't one in the input. They won't get upset when you feed it documents without that trailing newline and process them correctly. However, the line count when doing `cat | base64 -d` will differ before and after.

**Closed as completed by jelmervdl** 2020-05-18 13:00 UTC
